// Shared SEO helpers: NAP data, schema.org builders, and metadata sanitizers.
//
// Administrative note: since 01/07/2025 (Nghị quyết 1682/NQ-UBTVQH15) Long An
// province was merged into Tây Ninh province and Đức Hòa district was dissolved
// into 7 new communes. "Xã Mỹ Hạnh, tỉnh Tây Ninh" is the current legal address;
// "Đức Hòa" / "Long An" remain high-volume search terms and are kept as aliases.

export const SITE_URL = 'https://vansao.com'

export const BUSINESS = {
    name: 'Vạn Sao',
    legalName: 'Vạn Sao',
    phone: '0866631679',
    phoneDisplay: '08 666 31679',
    email: 'vansao.contact@gmail.com',
    street: 'Xã Mỹ Hạnh',
    locality: 'Xã Mỹ Hạnh',
    region: 'Tỉnh Tây Ninh',
    country: 'VN',
    // Human-readable address used in the UI and in article bodies.
    addressLine: 'Xã Mỹ Hạnh, tỉnh Tây Ninh (Đức Hòa, Long An cũ)',
    openingHours: 'Mo-Su 08:30-17:00',
    openingHoursDisplay: '8h30 – 17h00, hỗ trợ 24/7',
    priceRange: '1.000.000₫ - 15.000.000₫',
    social: [
        'https://www.facebook.com/profile.php?id=61576379972366',
        'https://zalo.me/0866631679',
    ],
    // Legacy + current place names this business serves. Doubles as the
    // areaServed list in schema and as local keyword coverage.
    areaServed: [
        'Xã Mỹ Hạnh',
        'Đức Hòa',
        'Đức Hòa Đông',
        'Đức Hòa Thượng',
        'Mỹ Hạnh Nam',
        'Mỹ Hạnh Bắc',
        'Hậu Nghĩa',
        'Hòa Khánh',
        'Đức Lập',
        'Tỉnh Tây Ninh',
        'Long An',
        'TP. Hồ Chí Minh',
    ],
}

export const localBusinessSchema = {
    '@context': 'https://schema.org',
    '@type': 'ProfessionalService',
    '@id': `${SITE_URL}/#business`,
    name: BUSINESS.name,
    url: SITE_URL,
    logo: `${SITE_URL}/logo.png`,
    image: `${SITE_URL}/logo.png`,
    telephone: BUSINESS.phone,
    email: BUSINESS.email,
    priceRange: BUSINESS.priceRange,
    address: {
        '@type': 'PostalAddress',
        streetAddress: BUSINESS.street,
        addressLocality: BUSINESS.locality,
        addressRegion: BUSINESS.region,
        addressCountry: BUSINESS.country,
    },
    openingHoursSpecification: [{
        '@type': 'OpeningHoursSpecification',
        dayOfWeek: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'],
        opens: '08:30',
        closes: '17:00',
    }],
    areaServed: BUSINESS.areaServed.map(name => ({ '@type': 'Place', name })),
    sameAs: BUSINESS.social,
    description:
        'Vạn Sao thiết kế website chuẩn SEO, tổ chức sự kiện – tiệc cưới và chuyển dữ liệu web. ' +
        'Phục vụ doanh nghiệp tại xã Mỹ Hạnh, Đức Hòa (tỉnh Tây Ninh, Long An cũ) và TP. Hồ Chí Minh. ' +
        'Giá minh bạch, bàn giao đúng hẹn, bảo hành 2 năm.',
    knowsAbout: [
        'Thiết kế website',
        'Thiết kế website chuẩn SEO',
        'Tổ chức sự kiện',
        'Tiệc cưới',
        'Chuyển dữ liệu web',
        'SEO local',
        'Next.js',
    ],
    makesOffer: [
        { '@type': 'Offer', name: 'Web cơ bản', priceCurrency: 'VND', price: '1000000' },
        { '@type': 'Offer', name: 'Web bán hàng', priceCurrency: 'VND', price: '4000000' },
        { '@type': 'Offer', name: 'Web nâng cao', priceCurrency: 'VND', price: '8000000' },
    ],
}

// Junk that leaks into excerpts generated by the autopost pipeline.
const NOISE_PATTERNS = [
    /Ảnh\s*:\s*[^.]{0,60}?\/\s*(Pexels|Unsplash|Freepik)/gi,
    /Photo\s+by\s+[^.]{0,60}?\s+on\s+(Pexels|Unsplash)/gi,
    /\(Nguồn\s*:\s*[^)]{0,60}\)/gi,
]

export function stripHtml(html) {
    if (!html) return ''
    return html
        .replace(/<(script|style)[\s\S]*?<\/\1>/gi, ' ')
        .replace(/<[^>]*>/g, ' ')
        .replace(/&nbsp;/g, ' ')
        .replace(/&amp;/g, '&')
        .replace(/&quot;/g, '"')
        .replace(/&#0?39;|&apos;/g, "'")
        .replace(/&lt;/g, '<')
        .replace(/&gt;/g, '>')
        .replace(/\s+/g, ' ')
        .trim()
}

/**
 * Build a clean meta description.
 * Prefers the excerpt, falls back to the article body, drops photo-credit noise,
 * and cuts on a word boundary so Google does not truncate mid-word.
 */
export function cleanDescription(excerpt, content = '', max = 158) {
    let text = stripHtml(excerpt)
    if (text.length < 60) text = stripHtml(content)

    for (const pattern of NOISE_PATTERNS) text = text.replace(pattern, ' ')
    text = text.replace(/\s+/g, ' ').trim()

    // A heading pasted as the first sentence reads badly in SERPs; drop it when
    // the body continues past it.
    const afterHeading = text.replace(/^[^.?!]{10,90}[?:]\s+/, '')
    if (afterHeading.length > 80) text = afterHeading

    if (text.length <= max) return text
    const cut = text.slice(0, max)
    const lastSpace = cut.lastIndexOf(' ')
    return `${(lastSpace > max * 0.6 ? cut.slice(0, lastSpace) : cut).replace(/[,;:\-–—]$/, '')}…`
}

/**
 * Pull a Q&A list out of rendered post HTML.
 * Looks for an <h2> whose text mentions FAQ / câu hỏi thường gặp, then treats
 * each following <h3> as a question and the markup up to the next heading as
 * its answer. Returns [] when the post has no FAQ block.
 */
export function extractFaq(html) {
    if (!html) return []

    const faqHeading = /<h2[^>]*>((?:(?!<\/h2>)[\s\S])*?)<\/h2>/gi
    let start = -1
    let match
    while ((match = faqHeading.exec(html)) !== null) {
        const label = stripHtml(match[1]).toLowerCase()
        if (/faq|câu hỏi thường gặp|hỏi\s*[-–&]?\s*đáp/.test(label)) {
            start = faqHeading.lastIndex
            break
        }
    }
    if (start === -1) return []

    // The FAQ block ends at the next <h2>.
    const rest = html.slice(start)
    const nextH2 = rest.search(/<h2[\s>]/i)
    const block = nextH2 === -1 ? rest : rest.slice(0, nextH2)

    const items = []
    const qa = /<h3[^>]*>((?:(?!<\/h3>)[\s\S])*?)<\/h3>([\s\S]*?)(?=<h3[\s>]|$)/gi
    let pair
    while ((pair = qa.exec(block)) !== null) {
        const question = stripHtml(pair[1])
        const answer = stripHtml(pair[2])
        if (question && answer) items.push({ question, answer })
    }
    return items
}

/**
 * The post template already renders the title as the page <h1>, but posts
 * imported from WordPress repeat it inside the body. Demote those to <h2> so
 * each page ships exactly one h1.
 */
export function demoteContentH1(html) {
    if (!html) return ''
    return html
        .replace(/<h1(\s[^>]*)?>/gi, (_, attrs) => `<h2${attrs ?? ''}>`)
        .replace(/<\/h1>/gi, '</h2>')
}

export function faqSchema(items, pageUrl) {
    if (!items.length) return null
    return {
        '@context': 'https://schema.org',
        '@type': 'FAQPage',
        '@id': `${pageUrl}#faq`,
        mainEntity: items.map(({ question, answer }) => ({
            '@type': 'Question',
            name: question,
            acceptedAnswer: { '@type': 'Answer', text: answer },
        })),
    }
}

export function breadcrumbSchema(trail) {
    return {
        '@context': 'https://schema.org',
        '@type': 'BreadcrumbList',
        itemListElement: trail.map(({ name, url }, i) => ({
            '@type': 'ListItem',
            position: i + 1,
            name,
            item: url,
        })),
    }
}

/**
 * Derive per-post keywords from the title so posts stop inheriting the
 * site-wide keyword list, which made every article look like the same page.
 */
export function keywordsFromTitle(title, extra = []) {
    const stop = new Set([
        'và', 'của', 'cho', 'với', 'các', 'những', 'là', 'có', 'trong', 'khi',
        'được', 'này', 'đó', 'một', 'từ', 'về', 'tại', 'ra', 'sao', 'gì', 'không',
    ])
    const words = stripHtml(title)
        .toLowerCase()
        .replace(/[^\p{L}\p{N}\s]/gu, ' ')
        .split(/\s+/)
        .filter(w => w.length > 2 && !stop.has(w))

    const phrases = []
    for (let i = 0; i < words.length - 1; i++) phrases.push(`${words[i]} ${words[i + 1]}`)

    return [...new Set([...extra, ...phrases.slice(0, 6), ...words.slice(0, 6)])].slice(0, 12)
}
